development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  host: localhost
  pool: 5
  username: <%= Figaro.env.pg_username %>
  password: <%= Figaro.env.pg_password %>
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  host: localhost
  pool: 5
  username: <%= Figaro.env.pg_username %>
  password: <%= Figaro.env.pg_password %>
  template: template0
  
production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
